//! ST / Campaign import-export compatibility matrix helpers.
//!
//! Distinguishes intentional normalization from data loss during:
//! import → internal → export/serialize → re-import.

use serde::{Deserialize, Serialize};
use serde_json::Value;
use storyforge_domain::character::{Character, StCharacterData};
use storyforge_domain::preset::RegexScript;
use storyforge_domain::variables::extract_mvu_schema_from_extensions;
use storyforge_domain::world_info::WorldInfoBook;

/// Severity of a compatibility observation.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum CompatSeverity {
    /// Confirmed data loss / corruption risk that must be fixed or documented.
    Loss,
    /// Intentional StoryForge normalization (not treated as a bug).
    Intentional,
    /// Unknown / opaque field survived as opaque payload.
    Preserved,
    /// Input rejected fail-closed without store mutation.
    Rejected,
}

/// One row in the machine-readable compatibility matrix.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct CompatFinding {
    pub area: String,
    pub field_path: String,
    pub severity: CompatSeverity,
    pub detail: String,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub before: Option<Value>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub after: Option<Value>,
}

/// Aggregate report generated by tests or scripts.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct CompatReport {
    pub format_version: u32,
    pub generated_by: String,
    pub seed: Option<u64>,
    pub findings: Vec<CompatFinding>,
    pub summary: CompatSummary,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct CompatSummary {
    pub loss: usize,
    pub intentional: usize,
    pub preserved: usize,
    pub rejected: usize,
}

impl CompatReport {
    pub const FORMAT_VERSION: u32 = 1;

    pub fn new(generated_by: impl Into<String>, seed: Option<u64>) -> Self {
        Self {
            format_version: Self::FORMAT_VERSION,
            generated_by: generated_by.into(),
            seed,
            findings: Vec::new(),
            summary: CompatSummary {
                loss: 0,
                intentional: 0,
                preserved: 0,
                rejected: 0,
            },
        }
    }

    pub fn push(&mut self, finding: CompatFinding) {
        match finding.severity {
            CompatSeverity::Loss => self.summary.loss += 1,
            CompatSeverity::Intentional => self.summary.intentional += 1,
            CompatSeverity::Preserved => self.summary.preserved += 1,
            CompatSeverity::Rejected => self.summary.rejected += 1,
        }
        self.findings.push(finding);
    }

    pub fn has_losses(&self) -> bool {
        self.summary.loss > 0
    }

    pub fn to_json_pretty(&self) -> Result<String, serde_json::Error> {
        serde_json::to_string_pretty(self)
    }
}

/// Compare two ST-shaped character data payloads for semantic round-trip fidelity.
///
/// Paths under `intentional_paths` are recorded as intentional normalization, not loss.
pub fn compare_st_data(
    before: &Value,
    after: &Value,
    intentional_paths: &[&str],
) -> Vec<CompatFinding> {
    let mut findings = Vec::new();
    compare_value(
        "st.data",
        "",
        before,
        after,
        intentional_paths,
        &mut findings,
    );
    findings
}

/// Build a high-level inventory of fields StoryForge currently understands from a Character.
pub fn inventory_character(character: &Character) -> CompatReport {
    let mut report = CompatReport::new("inventory_character", None);

    for (path, present) in [
        ("name", !character.name.is_empty()),
        ("description", !character.description.is_empty()),
        ("personality", !character.personality.is_empty()),
        ("scenario", !character.scenario.is_empty()),
        ("first_mes", !character.first_mes.is_empty()),
        ("mes_example", !character.mes_example.is_empty()),
        ("system_prompt", !character.system_prompt.is_empty()),
        (
            "post_history_instructions",
            !character.post_history_instructions.is_empty(),
        ),
        ("tags", !character.tags.is_empty()),
        ("creator", !character.creator.is_empty()),
        ("character_version", !character.character_version.is_empty()),
        (
            "alternate_greetings",
            !character.alternate_greetings.is_empty(),
        ),
        ("extensions", !character.extensions.is_null()),
        ("raw_card_json", character.raw_card_json.is_object()),
        (
            "embedded_world_info",
            character.embedded_world_info.is_some(),
        ),
        ("renderable_assets", character.renderable_assets.is_some()),
    ] {
        if present {
            report.push(CompatFinding {
                area: "character".into(),
                field_path: path.into(),
                severity: CompatSeverity::Preserved,
                detail: "typed/internal field populated after import".into(),
                before: None,
                after: None,
            });
        }
    }

    if let Some(obj) = character.raw_card_json.as_object() {
        for key in obj.keys() {
            if matches!(
                key.as_str(),
                "name"
                    | "description"
                    | "personality"
                    | "scenario"
                    | "first_mes"
                    | "mes_example"
                    | "system_prompt"
                    | "post_history_instructions"
                    | "tags"
                    | "creator"
                    | "character_version"
                    | "alternate_greetings"
                    | "extensions"
                    | "character_book"
            ) {
                continue;
            }
            report.push(CompatFinding {
                area: "st.data.extra".into(),
                field_path: key.clone(),
                severity: CompatSeverity::Preserved,
                detail: "unknown ST data-level field retained via flatten extra/raw_card_json"
                    .into(),
                before: obj.get(key).cloned(),
                after: None,
            });
        }
    }

    if let Some(obj) = character.extensions.as_object() {
        for key in obj.keys() {
            report.push(CompatFinding {
                area: "extensions".into(),
                field_path: key.clone(),
                severity: CompatSeverity::Preserved,
                detail: "extension key retained opaquely".into(),
                before: obj.get(key).cloned(),
                after: None,
            });
        }
    }

    let scripts = character.scoped_regex_scripts();
    if !scripts.is_empty() {
        report.push(CompatFinding {
            area: "regex_scripts".into(),
            field_path: "extensions.regex_scripts".into(),
            severity: CompatSeverity::Preserved,
            detail: format!("{} scoped regex script(s) parsed", scripts.len()),
            before: None,
            after: None,
        });
    }

    let mvu = extract_mvu_schema_from_extensions(&character.extensions);
    if !mvu.is_empty() {
        report.push(CompatFinding {
            area: "mvu".into(),
            field_path: "extensions.stat_data|mvu.initvar|variables".into(),
            severity: CompatSeverity::Preserved,
            detail: format!("{} MVU/stat_data schema field(s) detected", mvu.len()),
            before: None,
            after: None,
        });
    }

    if let Some(book) = &character.embedded_world_info {
        report_world_book(&mut report, book);
    }

    report
}

fn report_world_book(report: &mut CompatReport, book: &WorldInfoBook) {
    report.push(CompatFinding {
        area: "character_book".into(),
        field_path: "entries".into(),
        severity: CompatSeverity::Preserved,
        detail: format!("{} world book entries imported", book.entries.len()),
        before: None,
        after: None,
    });
    if !book.metadata.is_empty() {
        for key in book.metadata.keys() {
            report.push(CompatFinding {
                area: "character_book.metadata".into(),
                field_path: key.clone(),
                severity: CompatSeverity::Preserved,
                detail: "book-level metadata retained".into(),
                before: book.metadata.get(key).cloned(),
                after: None,
            });
        }
    }
}

/// Compare a Character after import → export → re-import against the first import.
pub fn compare_character_roundtrip(original: &Character, roundtripped: &Character) -> CompatReport {
    let mut report = CompatReport::new("compare_character_roundtrip", None);

    // Intentional: new internal ids each import.
    if original.id != roundtripped.id {
        report.push(CompatFinding {
            area: "character".into(),
            field_path: "id".into(),
            severity: CompatSeverity::Intentional,
            detail: "Character.id is regenerated on every import".into(),
            before: Some(Value::String(original.id.as_str().to_string())),
            after: Some(Value::String(roundtripped.id.as_str().to_string())),
        });
    }

    for (path, left, right) in [
        ("name", original.name.as_str(), roundtripped.name.as_str()),
        (
            "description",
            original.description.as_str(),
            roundtripped.description.as_str(),
        ),
        (
            "personality",
            original.personality.as_str(),
            roundtripped.personality.as_str(),
        ),
        (
            "scenario",
            original.scenario.as_str(),
            roundtripped.scenario.as_str(),
        ),
        (
            "first_mes",
            original.first_mes.as_str(),
            roundtripped.first_mes.as_str(),
        ),
        (
            "mes_example",
            original.mes_example.as_str(),
            roundtripped.mes_example.as_str(),
        ),
        (
            "system_prompt",
            original.system_prompt.as_str(),
            roundtripped.system_prompt.as_str(),
        ),
        (
            "post_history_instructions",
            original.post_history_instructions.as_str(),
            roundtripped.post_history_instructions.as_str(),
        ),
        (
            "creator",
            original.creator.as_str(),
            roundtripped.creator.as_str(),
        ),
        (
            "character_version",
            original.character_version.as_str(),
            roundtripped.character_version.as_str(),
        ),
        (
            "spec_version",
            original.spec_version.as_str(),
            roundtripped.spec_version.as_str(),
        ),
    ] {
        if left != right {
            report.push(CompatFinding {
                area: "character".into(),
                field_path: path.into(),
                severity: CompatSeverity::Loss,
                detail: "typed field changed across round-trip".into(),
                before: Some(Value::String(left.to_string())),
                after: Some(Value::String(right.to_string())),
            });
        } else {
            report.push(CompatFinding {
                area: "character".into(),
                field_path: path.into(),
                severity: CompatSeverity::Preserved,
                detail: "typed field stable across round-trip".into(),
                before: None,
                after: None,
            });
        }
    }

    if original.tags != roundtripped.tags {
        report.push(CompatFinding {
            area: "character".into(),
            field_path: "tags".into(),
            severity: CompatSeverity::Loss,
            detail: "tags changed across round-trip".into(),
            before: Some(Value::Array(
                original
                    .tags
                    .iter()
                    .map(|t| Value::String(t.clone()))
                    .collect(),
            )),
            after: Some(Value::Array(
                roundtripped
                    .tags
                    .iter()
                    .map(|t| Value::String(t.clone()))
                    .collect(),
            )),
        });
    }

    if original.alternate_greetings != roundtripped.alternate_greetings {
        report.push(CompatFinding {
            area: "character".into(),
            field_path: "alternate_greetings".into(),
            severity: CompatSeverity::Loss,
            detail: "alternate_greetings changed across round-trip".into(),
            before: Some(Value::from(original.alternate_greetings.clone())),
            after: Some(Value::from(roundtripped.alternate_greetings.clone())),
        });
    }

    if original.extensions != roundtripped.extensions {
        // extensions may reorder object keys; compare canonical JSON.
        let left = canonicalize(&original.extensions);
        let right = canonicalize(&roundtripped.extensions);
        if left != right {
            report.push(CompatFinding {
                area: "extensions".into(),
                field_path: "extensions".into(),
                severity: CompatSeverity::Loss,
                detail: "extensions payload changed across round-trip".into(),
                before: Some(original.extensions.clone()),
                after: Some(roundtripped.extensions.clone()),
            });
        } else {
            report.push(CompatFinding {
                area: "extensions".into(),
                field_path: "extensions".into(),
                severity: CompatSeverity::Preserved,
                detail: "extensions payload stable (canonical)".into(),
                before: None,
                after: None,
            });
        }
    } else {
        report.push(CompatFinding {
            area: "extensions".into(),
            field_path: "extensions".into(),
            severity: CompatSeverity::Preserved,
            detail: "extensions payload stable".into(),
            before: None,
            after: None,
        });
    }

    // Unknown ST data-level fields via raw_card_json
    if let (Some(left), Some(right)) = (
        original.raw_card_json.as_object(),
        roundtripped.raw_card_json.as_object(),
    ) {
        for (key, value) in left {
            if is_known_st_data_key(key) {
                continue;
            }
            match right.get(key) {
                Some(after) if after == value => {
                    report.push(CompatFinding {
                        area: "st.data.extra".into(),
                        field_path: key.clone(),
                        severity: CompatSeverity::Preserved,
                        detail: "unknown data-level field survived round-trip".into(),
                        before: Some(value.clone()),
                        after: Some(after.clone()),
                    });
                }
                Some(after) => {
                    report.push(CompatFinding {
                        area: "st.data.extra".into(),
                        field_path: key.clone(),
                        severity: CompatSeverity::Loss,
                        detail: "unknown data-level field mutated".into(),
                        before: Some(value.clone()),
                        after: Some(after.clone()),
                    });
                }
                None => {
                    report.push(CompatFinding {
                        area: "st.data.extra".into(),
                        field_path: key.clone(),
                        severity: CompatSeverity::Loss,
                        detail: "unknown data-level field dropped".into(),
                        before: Some(value.clone()),
                        after: None,
                    });
                }
            }
        }
    }

    compare_regex_scripts(
        &mut report,
        &original.scoped_regex_scripts(),
        &roundtripped.scoped_regex_scripts(),
    );
    compare_world_books(
        &mut report,
        original.embedded_world_info.as_ref(),
        roundtripped.embedded_world_info.as_ref(),
    );

    // Position string → number is intentional normalization on export via to_st_entry.
    report.push(CompatFinding {
        area: "character_book.entry".into(),
        field_path: "position".into(),
        severity: CompatSeverity::Intentional,
        detail: "ST position may be normalized from string labels to numeric codes on export"
            .into(),
        before: None,
        after: None,
    });

    report
}

fn compare_regex_scripts(report: &mut CompatReport, left: &[RegexScript], right: &[RegexScript]) {
    if left.len() != right.len() {
        report.push(CompatFinding {
            area: "regex_scripts".into(),
            field_path: "extensions.regex_scripts".into(),
            severity: CompatSeverity::Loss,
            detail: format!(
                "scoped regex count changed: {} -> {}",
                left.len(),
                right.len()
            ),
            before: Some(Value::from(left.len() as u64)),
            after: Some(Value::from(right.len() as u64)),
        });
        return;
    }
    for (idx, (a, b)) in left.iter().zip(right.iter()).enumerate() {
        if a.id != b.id
            || a.find_regex != b.find_regex
            || a.replace_string != b.replace_string
            || a.placement_codes != b.placement_codes
            || a.markdown_only != b.markdown_only
            || a.prompt_only != b.prompt_only
            || a.run_on_edit != b.run_on_edit
            || a.substitute_regex != b.substitute_regex
            || a.trim_strings != b.trim_strings
            || a.min_depth != b.min_depth
            || a.max_depth != b.max_depth
        {
            report.push(CompatFinding {
                area: "regex_scripts".into(),
                field_path: format!("extensions.regex_scripts[{idx}]"),
                severity: CompatSeverity::Loss,
                detail: "scoped regex metadata changed".into(),
                before: Some(serde_json::json!({
                    "id": a.id,
                    "find": a.find_regex,
                    "replace": a.replace_string,
                    "placement": a.placement_codes,
                })),
                after: Some(serde_json::json!({
                    "id": b.id,
                    "find": b.find_regex,
                    "replace": b.replace_string,
                    "placement": b.placement_codes,
                })),
            });
        } else {
            report.push(CompatFinding {
                area: "regex_scripts".into(),
                field_path: format!("extensions.regex_scripts[{idx}]"),
                severity: CompatSeverity::Preserved,
                detail: "scoped regex metadata stable".into(),
                before: None,
                after: None,
            });
        }
    }
}

fn compare_world_books(
    report: &mut CompatReport,
    left: Option<&WorldInfoBook>,
    right: Option<&WorldInfoBook>,
) {
    match (left, right) {
        (None, None) => {}
        (Some(_), None) => {
            report.push(CompatFinding {
                area: "character_book".into(),
                field_path: "character_book".into(),
                severity: CompatSeverity::Loss,
                detail: "embedded world book dropped".into(),
                before: None,
                after: None,
            });
        }
        (None, Some(_)) => {
            report.push(CompatFinding {
                area: "character_book".into(),
                field_path: "character_book".into(),
                severity: CompatSeverity::Loss,
                detail: "embedded world book unexpectedly appeared".into(),
                before: None,
                after: None,
            });
        }
        (Some(a), Some(b)) => {
            if a.metadata != b.metadata {
                report.push(CompatFinding {
                    area: "character_book.metadata".into(),
                    field_path: "character_book.extra".into(),
                    severity: CompatSeverity::Loss,
                    detail: "book-level metadata changed or dropped".into(),
                    before: Some(Value::Object(a.metadata.clone().into_iter().collect())),
                    after: Some(Value::Object(b.metadata.clone().into_iter().collect())),
                });
            } else if !a.metadata.is_empty() {
                report.push(CompatFinding {
                    area: "character_book.metadata".into(),
                    field_path: "character_book.extra".into(),
                    severity: CompatSeverity::Preserved,
                    detail: "book-level metadata stable".into(),
                    before: None,
                    after: None,
                });
            }

            if a.entries.len() != b.entries.len() {
                report.push(CompatFinding {
                    area: "character_book".into(),
                    field_path: "entries".into(),
                    severity: CompatSeverity::Loss,
                    detail: format!(
                        "world book entry count changed: {} -> {}",
                        a.entries.len(),
                        b.entries.len()
                    ),
                    before: Some(Value::from(a.entries.len() as u64)),
                    after: Some(Value::from(b.entries.len() as u64)),
                });
                return;
            }

            for (idx, (le, re)) in a.entries.iter().zip(b.entries.iter()).enumerate() {
                let mut entry_loss = false;
                if le.keys != re.keys
                    || le.secondary_keys != re.secondary_keys
                    || le.content != re.content
                    || le.constant != re.constant
                    || le.selective != re.selective
                    || le.selective_logic != re.selective_logic
                    || le.order != re.order
                    || le.depth != re.depth
                    || le.st_id != re.st_id
                    || canonicalize(&le.extensions) != canonicalize(&re.extensions)
                {
                    entry_loss = true;
                }
                // position may be intentionally normalized (string label → number).
                if le.position != re.position {
                    report.push(CompatFinding {
                        area: "character_book.entry".into(),
                        field_path: format!("entries[{idx}].position"),
                        severity: CompatSeverity::Intentional,
                        detail: "position normalized between ST string labels and numeric codes"
                            .into(),
                        before: Some(Value::from(le.position)),
                        after: Some(Value::from(re.position)),
                    });
                }
                if entry_loss {
                    report.push(CompatFinding {
                        area: "character_book.entry".into(),
                        field_path: format!("entries[{idx}]"),
                        severity: CompatSeverity::Loss,
                        detail: "world book entry fields changed".into(),
                        before: Some(serde_json::json!({
                            "keys": le.keys,
                            "secondary_keys": le.secondary_keys,
                            "content": le.content,
                            "constant": le.constant,
                            "selective": le.selective,
                            "order": le.order,
                            "depth": le.depth,
                            "st_id": le.st_id,
                        })),
                        after: Some(serde_json::json!({
                            "keys": re.keys,
                            "secondary_keys": re.secondary_keys,
                            "content": re.content,
                            "constant": re.constant,
                            "selective": re.selective,
                            "order": re.order,
                            "depth": re.depth,
                            "st_id": re.st_id,
                        })),
                    });
                } else {
                    report.push(CompatFinding {
                        area: "character_book.entry".into(),
                        field_path: format!("entries[{idx}]"),
                        severity: CompatSeverity::Preserved,
                        detail: "world book entry stable".into(),
                        before: None,
                        after: None,
                    });
                }
            }
        }
    }
}

fn is_known_st_data_key(key: &str) -> bool {
    matches!(
        key,
        "name"
            | "description"
            | "personality"
            | "scenario"
            | "first_mes"
            | "mes_example"
            | "system_prompt"
            | "post_history_instructions"
            | "tags"
            | "creator"
            | "character_version"
            | "alternate_greetings"
            | "extensions"
            | "character_book"
    )
}

fn canonicalize(value: &Value) -> Value {
    match value {
        Value::Object(map) => {
            let mut keys: Vec<_> = map.keys().cloned().collect();
            keys.sort();
            let mut out = serde_json::Map::new();
            for key in keys {
                if let Some(v) = map.get(&key) {
                    out.insert(key, canonicalize(v));
                }
            }
            Value::Object(out)
        }
        Value::Array(items) => Value::Array(items.iter().map(canonicalize).collect()),
        other => other.clone(),
    }
}

fn path_is_intentional(path: &str, full: &str, intentional_paths: &[&str]) -> bool {
    intentional_paths.iter().any(|p| {
        *p == path
            || full == *p
            || full.ends_with(&format!(".{p}"))
            || path.ends_with(&format!(".{p}"))
    })
}

fn compare_value(
    area: &str,
    path: &str,
    before: &Value,
    after: &Value,
    intentional_paths: &[&str],
    out: &mut Vec<CompatFinding>,
) {
    let full = if path.is_empty() {
        area.to_string()
    } else {
        format!("{area}.{path}")
    };
    if path_is_intentional(path, &full, intentional_paths) {
        if before != after {
            out.push(CompatFinding {
                area: area.into(),
                field_path: path.into(),
                severity: CompatSeverity::Intentional,
                detail: "listed intentional normalization path".into(),
                before: Some(before.clone()),
                after: Some(after.clone()),
            });
        }
        return;
    }

    match (before, after) {
        (Value::Object(a), Value::Object(b)) => {
            for (key, av) in a {
                let child = if path.is_empty() {
                    key.clone()
                } else {
                    format!("{path}.{key}")
                };
                let child_full = format!("{area}.{child}");
                match b.get(key) {
                    Some(bv) => compare_value(area, &child, av, bv, intentional_paths, out),
                    None if path_is_intentional(&child, &child_full, intentional_paths) => {
                        out.push(CompatFinding {
                            area: area.into(),
                            field_path: child,
                            severity: CompatSeverity::Intentional,
                            detail: "listed intentional normalization path dropped/normalized"
                                .into(),
                            before: Some(av.clone()),
                            after: None,
                        });
                    }
                    None => out.push(CompatFinding {
                        area: area.into(),
                        field_path: child,
                        severity: CompatSeverity::Loss,
                        detail: "object field dropped".into(),
                        before: Some(av.clone()),
                        after: None,
                    }),
                }
            }
            for (key, bv) in b {
                if !a.contains_key(key) {
                    let child = if path.is_empty() {
                        key.clone()
                    } else {
                        format!("{path}.{key}")
                    };
                    out.push(CompatFinding {
                        area: area.into(),
                        field_path: child,
                        severity: CompatSeverity::Intentional,
                        detail: "object field added during export/import".into(),
                        before: None,
                        after: Some(bv.clone()),
                    });
                }
            }
        }
        (Value::Array(a), Value::Array(b)) => {
            if a.len() != b.len() {
                out.push(CompatFinding {
                    area: area.into(),
                    field_path: path.into(),
                    severity: CompatSeverity::Loss,
                    detail: format!("array length changed: {} -> {}", a.len(), b.len()),
                    before: Some(before.clone()),
                    after: Some(after.clone()),
                });
                return;
            }
            for (i, (av, bv)) in a.iter().zip(b.iter()).enumerate() {
                let child = format!("{path}[{i}]");
                compare_value(area, &child, av, bv, intentional_paths, out);
            }
        }
        (a, b) if a == b => {
            out.push(CompatFinding {
                area: area.into(),
                field_path: path.into(),
                severity: CompatSeverity::Preserved,
                detail: "value stable".into(),
                before: None,
                after: None,
            });
        }
        (a, b) => {
            out.push(CompatFinding {
                area: area.into(),
                field_path: path.into(),
                severity: CompatSeverity::Loss,
                detail: "value changed".into(),
                before: Some(a.clone()),
                after: Some(b.clone()),
            });
        }
    }
}

/// Serialize StCharacterData for semantic comparison helpers.
pub fn st_data_to_value(data: &StCharacterData) -> Value {
    serde_json::to_value(data).unwrap_or(Value::Null)
}

/// Deterministic pseudo-random for bounded property tests (xorshift64*).
#[derive(Debug, Clone)]
pub struct SeedRng {
    state: u64,
}

impl SeedRng {
    pub fn new(seed: u64) -> Self {
        Self {
            state: if seed == 0 {
                0x9E37_79B9_7F4A_7C15
            } else {
                seed
            },
        }
    }

    pub fn next_u64(&mut self) -> u64 {
        let mut x = self.state;
        x ^= x >> 12;
        x ^= x << 25;
        x ^= x >> 27;
        self.state = x;
        x.wrapping_mul(0x2545_F491_4F6C_DD1D)
    }

    pub fn next_usize(&mut self, max: usize) -> usize {
        if max == 0 {
            return 0;
        }
        (self.next_u64() as usize) % max
    }

    pub fn next_bool(&mut self) -> bool {
        self.next_u64() & 1 == 1
    }

    pub fn next_string(&mut self, max_len: usize) -> String {
        const ALPHABET: &[u8] =
            b"abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789_-<>/";
        let len = self.next_usize(max_len.saturating_add(1));
        (0..len)
            .map(|_| ALPHABET[self.next_usize(ALPHABET.len())] as char)
            .collect()
    }
}

/// Generate a minimal hostile-but-bounded ST card JSON for property tests.
pub fn generate_edge_card_json(rng: &mut SeedRng) -> Value {
    let name = format!("fuzz-{}", rng.next_string(12));
    let alt_count = rng.next_usize(4);
    let mut alternate_greetings = Vec::new();
    for _ in 0..alt_count {
        alternate_greetings.push(Value::String(rng.next_string(48)));
    }

    let entry_count = rng.next_usize(5);
    let mut entries = Vec::new();
    for i in 0..entry_count {
        entries.push(serde_json::json!({
            "id": i as i32,
            "keys": [rng.next_string(8), rng.next_string(8)],
            "secondary_keys": if rng.next_bool() { vec![rng.next_string(6)] } else { vec![] },
            "content": rng.next_string(64),
            "constant": rng.next_bool(),
            "selective": rng.next_bool(),
            "selective_logic": rng.next_usize(3) as i32,
            "position": if rng.next_bool() { Value::String("after_char".into()) } else { Value::from(1) },
            "order": rng.next_usize(200) as i32,
            "depth": rng.next_usize(8) as i32,
            "extensions": {
                "entry_extra": { "seed": rng.next_u64() }
            }
        }));
    }

    let hostile_regex = if rng.next_bool() {
        r#"(?s)<script>.*?</script>"#
    } else {
        r#"/<img[^>]*>/gi"#
    };

    serde_json::json!({
        "spec": "chara_card_v2",
        "spec_version": if rng.next_bool() { "3.0" } else { "2.0" },
        "data": {
            "name": name,
            "description": rng.next_string(80),
            "personality": rng.next_string(40),
            "scenario": rng.next_string(40),
            "first_mes": rng.next_string(40),
            "mes_example": rng.next_string(20),
            "system_prompt": rng.next_string(30),
            "post_history_instructions": rng.next_string(20),
            "tags": [rng.next_string(8), "fuzz"],
            "creator": "compat-fuzz",
            "character_version": format!("{}", rng.next_usize(9)),
            "alternate_greetings": alternate_greetings,
            "group_only": rng.next_bool(),
            "creator_notes": rng.next_string(24),
            "extensions": {
                "unknown_plugin": { "flag": rng.next_bool(), "n": rng.next_u64() },
                "stat_data": { "hp": rng.next_usize(200) as i64, "mood": rng.next_string(8) },
                "regex_scripts": [{
                    "id": format!("fuzz-{}", rng.next_string(6)),
                    "scriptName": "Hostile cleanup",
                    "findRegex": hostile_regex,
                    "replaceString": "",
                    "placement": [1, 2],
                    "disabled": false,
                    "markdownOnly": rng.next_bool(),
                    "promptOnly": rng.next_bool()
                }]
            },
            "character_book": {
                "name": format!("book-{}", rng.next_string(6)),
                "description": rng.next_string(20),
                "scan_depth": rng.next_usize(20) as i32,
                "extensions": { "book_plugin": { "on": true } },
                "entries": entries
            }
        }
    })
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::{import_character, import_character_from_json, png};
    use storyforge_domain::character::to_st_data;

    fn sample_card_json() -> Value {
        serde_json::json!({
            "spec": "chara_card_v2",
            "spec_version": "3.0",
            "data": {
                "name": "Compat Matrix",
                "description": "matrix fixture",
                "personality": "steady",
                "scenario": "lab",
                "first_mes": "hello",
                "mes_example": "ex",
                "system_prompt": "sys",
                "post_history_instructions": "phi",
                "tags": ["a", "b"],
                "creator": "sf",
                "character_version": "1",
                "alternate_greetings": ["alt"],
                "group_only": true,
                "creator_notes": "keep",
                "extensions": {
                    "stat_data": {"hp": 12, "mood": "calm"},
                    "regex_scripts": [{
                        "id": "r1",
                        "scriptName": "clean",
                        "findRegex": "foo",
                        "replaceString": "bar",
                        "placement": [2],
                        "disabled": false,
                        "promptOnly": true
                    }],
                    "unknown_plugin": {"x": 1}
                },
                "character_book": {
                    "name": "Matrix Book",
                    "description": "book meta",
                    "scan_depth": 7,
                    "extensions": {"book_plugin": {"enabled": true}},
                    "entries": [{
                        "id": 3,
                        "keys": ["alpha"],
                        "secondary_keys": ["beta"],
                        "content": "lore",
                        "selective": true,
                        "selective_logic": 1,
                        "position": "after_char",
                        "order": 9,
                        "depth": 4,
                        "extensions": {"entry_extra": 1}
                    }]
                }
            }
        })
    }

    #[test]
    fn utf8_bom_prefixed_json_imports_successfully() {
        let mut bytes = vec![0xEF, 0xBB, 0xBF];
        bytes.extend(serde_json::to_vec(&sample_card_json()).unwrap());
        let character = import_character_from_json(&bytes).expect("BOM JSON should import");
        assert_eq!(character.name, "Compat Matrix");
        assert_eq!(character.raw_card_json["group_only"], true);
    }

    #[test]
    fn world_book_metadata_survives_import_export_reimport() {
        let imported =
            import_character_from_json(&serde_json::to_vec(&sample_card_json()).unwrap()).unwrap();
        let book = imported
            .embedded_world_info
            .as_ref()
            .expect("book should import");
        assert_eq!(
            book.metadata.get("name").and_then(|v| v.as_str()),
            Some("Matrix Book")
        );
        assert_eq!(
            book.metadata.get("description").and_then(|v| v.as_str()),
            Some("book meta")
        );
        assert_eq!(book.metadata.get("scan_depth"), Some(&Value::from(7)));
        assert_eq!(book.metadata["extensions"]["book_plugin"]["enabled"], true);

        let exported = to_st_data(&imported, None, Some(book.to_st_book()));
        let st_card = png::make_st_card(exported, &imported.spec_version);
        let png_bytes = png::write_st_card_png(&st_card, None).unwrap();
        let round = import_character(&png_bytes).unwrap();
        let round_book = round.embedded_world_info.as_ref().unwrap();
        assert_eq!(
            round_book.metadata.get("name").and_then(|v| v.as_str()),
            Some("Matrix Book")
        );
        assert_eq!(
            round_book.metadata["extensions"]["book_plugin"]["enabled"],
            true
        );
    }

    #[test]
    fn semantic_roundtrip_report_has_no_losses_for_matrix_fixture() {
        let imported =
            import_character_from_json(&serde_json::to_vec(&sample_card_json()).unwrap()).unwrap();
        let exported = to_st_data(
            &imported,
            None,
            imported
                .embedded_world_info
                .as_ref()
                .map(|b| b.to_st_book()),
        );
        let st_card = png::make_st_card(exported, &imported.spec_version);
        let png_bytes = png::write_st_card_png(&st_card, None).unwrap();
        let round = import_character(&png_bytes).unwrap();
        let report = compare_character_roundtrip(&imported, &round);
        assert!(
            !report.has_losses(),
            "unexpected losses: {}",
            report.to_json_pretty().unwrap()
        );
        assert!(report.summary.preserved > 0);
    }

    #[test]
    fn inventory_and_report_are_machine_readable_json() {
        let imported =
            import_character_from_json(&serde_json::to_vec(&sample_card_json()).unwrap()).unwrap();
        let report = inventory_character(&imported);
        let json = report.to_json_pretty().unwrap();
        let parsed: CompatReport = serde_json::from_str(&json).unwrap();
        assert_eq!(parsed.format_version, CompatReport::FORMAT_VERSION);
        assert!(parsed.summary.preserved > 0);
        assert!(
            parsed
                .findings
                .iter()
                .any(|f| f.area == "mvu" || f.field_path.contains("stat_data"))
        );
    }

    #[test]
    fn st_key_aliases_key_and_keysecondary_import() {
        let json = serde_json::json!({
            "spec": "chara_card_v2",
            "spec_version": "3.0",
            "data": {
                "name": "Alias Keys",
                "character_book": {
                    "entries": [{
                        "id": 1,
                        "key": ["primary-a", "primary-b"],
                        "keysecondary": "secondary-a, secondary-b",
                        "content": "alias lore",
                        "selective": true
                    }]
                }
            }
        });
        let character =
            import_character_from_json(&serde_json::to_vec(&json).unwrap()).expect("alias card");
        let book = character.embedded_world_info.expect("book");
        assert_eq!(book.entries[0].keys, vec!["primary-a", "primary-b"]);
        assert_eq!(
            book.entries[0].secondary_keys,
            vec!["secondary-a", "secondary-b"]
        );
    }

    #[test]
    fn first_import_from_source_json_preserves_alias_keys_and_book_meta() {
        // Compare SOURCE JSON → first import, not import → reimport.
        // Catches losses that already happen on the initial parse/normalize step.
        let source = serde_json::json!({
            "spec": "chara_card_v2",
            "spec_version": "3.0",
            "data": {
                "name": "Source Fidelity",
                "group_only": true,
                "creator_notes": "keep me",
                "extensions": {
                    "stat_data": {"hp": 9},
                    "unknown_plugin": {"x": 1}
                },
                "character_book": {
                    "name": "Source Book",
                    "description": "from source",
                    "scan_depth": 4,
                    "extensions": {"book_plugin": {"on": true}},
                    "entries": [{
                        "id": 1,
                        "key": ["alpha", "beta"],
                        "keysecondary": "sec-a, sec-b",
                        "content": "alias lore",
                        "selective": true,
                        "position": "after_char",
                        "order": 3,
                        "depth": 2,
                        "extensions": {"entry_extra": 7}
                    }]
                }
            }
        });
        let imported =
            import_character_from_json(&serde_json::to_vec(&source).unwrap()).expect("import");

        assert_eq!(imported.raw_card_json["group_only"], true);
        assert_eq!(imported.raw_card_json["creator_notes"], "keep me");
        assert_eq!(
            imported.raw_card_json["character_book"]["name"],
            "Source Book"
        );
        assert_eq!(
            imported.raw_card_json["character_book"]["entries"][0]["keys"],
            serde_json::json!(["alpha", "beta"]),
            "first import must materialize legacy key aliases into keys in raw_card_json"
        );
        assert_eq!(
            imported.raw_card_json["character_book"]["entries"][0]["secondary_keys"],
            serde_json::json!(["sec-a", "sec-b"])
        );

        let book = imported.embedded_world_info.as_ref().expect("book");
        assert_eq!(book.entries[0].keys, vec!["alpha", "beta"]);
        assert_eq!(book.entries[0].secondary_keys, vec!["sec-a", "sec-b"]);
        assert_eq!(
            book.metadata.get("name").and_then(|v| v.as_str()),
            Some("Source Book")
        );

        // Source-vs-first-import semantic compare for opaque extras / extensions.
        let source_data = &source["data"];
        // Legacy aliases are intentionally normalized into canonical keys /
        // secondary_keys on first import; the path suffix match in compare_st_data
        // treats these as intentional, not loss.
        let report = compare_st_data(
            source_data,
            &imported.raw_card_json,
            &["key", "keysecondary", "position"],
        );
        let losses: Vec<_> = report
            .into_iter()
            .filter(|f| f.severity == CompatSeverity::Loss)
            .collect();
        assert!(losses.is_empty(), "source→first-import losses: {losses:?}");
    }

    #[test]
    fn oversized_import_is_rejected() {
        let mut huge = Vec::new();
        huge.extend_from_slice(br#"{"spec":"chara_card_v2","data":{"name":""#);
        huge.extend(std::iter::repeat_n(b'A', crate::MAX_IMPORT_SIZE + 8));
        huge.extend_from_slice(br#""}}"#);
        let err = import_character(&huge).expect_err("oversized should fail");
        assert!(matches!(err, crate::ImportError::PngError(_)));
    }

    #[test]
    fn malformed_json_and_truncated_png_fail_closed() {
        let err = import_character_from_json(br#"{"spec":"chara_card_v2","data":{"name":"x"}"#)
            .expect_err("truncated json");
        assert!(matches!(err, crate::ImportError::JsonError(_)));

        let mut png = png::build_placeholder_png();
        png.truncate(png.len().saturating_sub(4));
        let err = import_character(&png).expect_err("truncated png");
        assert!(matches!(
            err,
            crate::ImportError::PngError(_) | crate::ImportError::NoCharacterData
        ));
    }

    #[test]
    fn bounded_property_suite_roundtrips_without_loss() {
        const SEED: u64 = 0xC0A7_5EED;
        let mut rng = SeedRng::new(SEED);
        let mut aggregate = CompatReport::new("bounded_property_suite", Some(SEED));
        for i in 0..24 {
            let card = generate_edge_card_json(&mut rng);
            let bytes = serde_json::to_vec(&card).unwrap();
            let imported = import_character_from_json(&bytes)
                .unwrap_or_else(|e| panic!("seed={SEED} case={i} import failed: {e}"));
            let exported = to_st_data(
                &imported,
                None,
                imported
                    .embedded_world_info
                    .as_ref()
                    .map(|b| b.to_st_book()),
            );
            let st_card = png::make_st_card(exported, &imported.spec_version);
            let png_bytes = png::write_st_card_png(&st_card, None)
                .unwrap_or_else(|e| panic!("seed={SEED} case={i} png export failed: {e}"));
            let round = import_character(&png_bytes)
                .unwrap_or_else(|e| panic!("seed={SEED} case={i} reimport failed: {e}"));
            let report = compare_character_roundtrip(&imported, &round);
            if report.has_losses() {
                panic!(
                    "seed={SEED} case={i} losses:\n{}",
                    report.to_json_pretty().unwrap()
                );
            }
            for finding in report.findings {
                aggregate.push(finding);
            }
        }
        assert!(aggregate.summary.preserved > 0);
        assert_eq!(aggregate.summary.loss, 0);
    }
}
